name: 🧑‍💻 Onboard my repository
description: Add a repository to the Belux Engineering Experience community.
title: "[Onboarding] Adding new repository"
labels: ["Onboarding"]
body:
  - type: input
    id: repo-url
    attributes:
      label: Repository Url
      description: URL of you public repository
    validations:
      required: true
  - type: checkboxes
    id: solution-areas
    attributes:
      label: Related solution areas (CTRL + click to select multiple)
      options:
        - label: Infrastructure
        - label: Application Innovation
        - label: Data & AI
        - label: Security
        - label: Modern Workplace
        - label: Dynamics 365
        - label: Other
