name: 🧑‍💻 Onboard my repository
description: Add a repository to the Belux Engineering Experience community.
title: "[Onboarding] Adding new repository"
labels: ["onboarding"]
body:
  - type: input
    id: repo-url
    attributes:
      label: Repository Url
      description: URL of you public repository
    validations:
      required: true
  - type: input
    id: repo-description
    attributes:
      label: Repository description
      description: Short description of what your repository is about. Your chance to market your work 😉
    validations:
      required: true
  - type: checkboxes
    id: solution-areas
    attributes:
      label: Related solution areas
      options:
        - label: Infrastructure
        - label: Application Innovation
        - label: AI
        - label: Data
        - label: Security
        - label: Modern Workplace
        - label: Dynamics 365
        - label: Other
    validations:
      required: true
