name: Update Commit Metrics Dashboard

on:
  schedule:
    - cron: '0 4 * * *'  # Every day at 4am UTC
  workflow_dispatch:

jobs:
  update-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4.9.1
      - run: pip install -r activity-dashboard/requirements.txt
      - run: python activity-dashboard/update_metrics_dashboard.py
      - uses: actions4git/setup-git@v1
        name: Setup git
      - name: Commit and push changes
        run: |
          git add activity-dashboard/README.md
          git commit -m "Updated Metrics Dashboard"
          git push origin main
          echo "Activity dashboard updated successfully!"
