
name: 🚧 Generate README
on:
  workflow_dispatch:

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4.9.1
      - run: pip install -r requirements.txt
      - run: python readme_generator/generate_readme.py
      - uses: actions4git/setup-git@v1
        name: Setup git
      - name: Commit readme
        run: |
          git add README.md
          git commit -m "Updated readme"
          git push origin main
          echo "Repository added successfully!"
